# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = LabCD
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"." \
    -lgdal_i \
    -lopencv_world455 \
    -lopencv_world455d
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += .
include(LabCD.pri)
